[project]
name = "calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "agent>=0.1.3",
    "dotenv>=0.9.9",
    "openai-agents>=0.0.16",
    "typing>=3.10.0.0",
]
